
// Auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const TOKEN_FAIL = "TOKEN_FAIL";
export const APP_INITIALISED = "APP_INITIALISED";

// Category
export const CATEGORIES_FETCHED = "CATEGORIES_FETCHED";
export const QUERIED_CATEGORIES_FETCHED = "QUERIED_CATEGORIES_FETCHED";
export const CLEAR_QUERIED_CATEGORIES = "CLEAR_QUERIED_CATEGORIES";
export const CATEGORY_ADDED = "CATEGORY_ADDED";

// Product
export const PRODUCT_ADDED = "PRODUCT_ADDED";